project:
  type: book

book:
  title: "Curso de Análisis de Jordan"
  author: "M. E. Camille Jordan"
  date: "15/9/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



